apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-name
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        name: external-gw
      envoyService:
        name: external-gw